inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
